/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AccountCartList200ResponseResult
import org.openapitools.client.models.AccountCartList200ResponseResultCartsInner

class AccountCartList200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountCartList200ResponseResult
        //val modelInstance = AccountCartList200ResponseResult()

        // to test the property `cartsCount`
        should("test cartsCount") {
            // uncomment below to test the property
            //modelInstance.cartsCount shouldBe ("TODO")
        }

        // to test the property `carts`
        should("test carts") {
            // uncomment below to test the property
            //modelInstance.carts shouldBe ("TODO")
        }

    }
}
