/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner
import org.openapitools.client.models.AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams

class AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner
        //val modelInstance = AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner()

        // to test the property `cartId`
        should("test cartId") {
            // uncomment below to test the property
            //modelInstance.cartId shouldBe ("TODO")
        }

        // to test the property `cartName`
        should("test cartName") {
            // uncomment below to test the property
            //modelInstance.cartName shouldBe ("TODO")
        }

        // to test the property `cartVersions`
        should("test cartVersions") {
            // uncomment below to test the property
            //modelInstance.cartVersions shouldBe ("TODO")
        }

        // to test the property `cartMethod`
        should("test cartMethod") {
            // uncomment below to test the property
            //modelInstance.cartMethod shouldBe ("TODO")
        }

        // to test the property `params`
        should("test params") {
            // uncomment below to test the property
            //modelInstance.params shouldBe ("TODO")
        }

    }
}
