/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AccountCartAddHybrisWebsitesInner

class AccountCartAddHybrisWebsitesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountCartAddHybrisWebsitesInner
        //val modelInstance = AccountCartAddHybrisWebsitesInner()

        // to test the property `uid`
        should("test uid") {
            // uncomment below to test the property
            //modelInstance.uid shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `storeIds`
        should("test storeIds") {
            // uncomment below to test the property
            //modelInstance.storeIds shouldBe ("TODO")
        }

    }
}
