/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Basket
import org.openapitools.client.models.A2CDateTime
import org.openapitools.client.models.BaseCustomer
import org.openapitools.client.models.BasketItem
import org.openapitools.client.models.Currency

class BasketTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Basket
        //val modelInstance = Basket()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `customer`
        should("test customer") {
            // uncomment below to test the property
            //modelInstance.customer shouldBe ("TODO")
        }

        // to test the property `basketUrl`
        should("test basketUrl") {
            // uncomment below to test the property
            //modelInstance.basketUrl shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `modifiedAt`
        should("test modifiedAt") {
            // uncomment below to test the property
            //modelInstance.modifiedAt shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `basketProducts`
        should("test basketProducts") {
            // uncomment below to test the property
            //modelInstance.basketProducts shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
