/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BasketItem
import org.openapitools.client.models.BasketItemOption

class BasketItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BasketItem
        //val modelInstance = BasketItem()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `parentId`
        should("test parentId") {
            // uncomment below to test the property
            //modelInstance.parentId shouldBe ("TODO")
        }

        // to test the property `productId`
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `variantId`
        should("test variantId") {
            // uncomment below to test the property
            //modelInstance.variantId shouldBe ("TODO")
        }

        // to test the property `sku`
        should("test sku") {
            // uncomment below to test the property
            //modelInstance.sku shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `tax`
        should("test tax") {
            // uncomment below to test the property
            //modelInstance.tax shouldBe ("TODO")
        }

        // to test the property `quantity`
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `weightUnit`
        should("test weightUnit") {
            // uncomment below to test the property
            //modelInstance.weightUnit shouldBe ("TODO")
        }

        // to test the property `weight`
        should("test weight") {
            // uncomment below to test the property
            //modelInstance.weight shouldBe ("TODO")
        }

        // to test the property `options`
        should("test options") {
            // uncomment below to test the property
            //modelInstance.options shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
