/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CartClearCache200ResponseResult

class CartClearCache200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CartClearCache200ResponseResult
        //val modelInstance = CartClearCache200ResponseResult()

        // to test the property `cacheCleared`
        should("test cacheCleared") {
            // uncomment below to test the property
            //modelInstance.cacheCleared shouldBe ("TODO")
        }

    }
}
