/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CartShippingMethodRate

class CartShippingMethodRateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CartShippingMethodRate
        //val modelInstance = CartShippingMethodRate()

        // to test the property `minWeight`
        should("test minWeight") {
            // uncomment below to test the property
            //modelInstance.minWeight shouldBe ("TODO")
        }

        // to test the property `maxWeight`
        should("test maxWeight") {
            // uncomment below to test the property
            //modelInstance.maxWeight shouldBe ("TODO")
        }

        // to test the property `minOrderAmount`
        should("test minOrderAmount") {
            // uncomment below to test the property
            //modelInstance.minOrderAmount shouldBe ("TODO")
        }

        // to test the property `maxOrderAmount`
        should("test maxOrderAmount") {
            // uncomment below to test the property
            //modelInstance.maxOrderAmount shouldBe ("TODO")
        }

        // to test the property `minItemsCount`
        should("test minItemsCount") {
            // uncomment below to test the property
            //modelInstance.minItemsCount shouldBe ("TODO")
        }

        // to test the property `maxItemsCount`
        should("test maxItemsCount") {
            // uncomment below to test the property
            //modelInstance.maxItemsCount shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
