/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CartPluginList200ResponseResult
import org.openapitools.client.models.PluginList

class CartPluginList200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CartPluginList200ResponseResult
        //val modelInstance = CartPluginList200ResponseResult()

        // to test the property `allPlugins`
        should("test allPlugins") {
            // uncomment below to test the property
            //modelInstance.allPlugins shouldBe ("TODO")
        }

        // to test the property `plugins`
        should("test plugins") {
            // uncomment below to test the property
            //modelInstance.plugins shouldBe ("TODO")
        }

    }
}
