/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CartGiftcardCount200ResponseResult

class CartGiftcardCount200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CartGiftcardCount200ResponseResult
        //val modelInstance = CartGiftcardCount200ResponseResult()

        // to test the property `giftCardsCount`
        should("test giftCardsCount") {
            // uncomment below to test the property
            //modelInstance.giftCardsCount shouldBe ("TODO")
        }

    }
}
