/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CatalogPriceRule
import org.openapitools.client.models.A2CDateTime
import org.openapitools.client.models.CatalogPriceRuleAction
import org.openapitools.client.models.CouponCondition

class CatalogPriceRuleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CatalogPriceRule
        //val modelInstance = CatalogPriceRule()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `gid`
        should("test gid") {
            // uncomment below to test the property
            //modelInstance.gid shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `shortDescription`
        should("test shortDescription") {
            // uncomment below to test the property
            //modelInstance.shortDescription shouldBe ("TODO")
        }

        // to test the property `avail`
        should("test avail") {
            // uncomment below to test the property
            //modelInstance.avail shouldBe ("TODO")
        }

        // to test the property `actions`
        should("test actions") {
            // uncomment below to test the property
            //modelInstance.actions shouldBe ("TODO")
        }

        // to test the property `createdTime`
        should("test createdTime") {
            // uncomment below to test the property
            //modelInstance.createdTime shouldBe ("TODO")
        }

        // to test the property `dateStart`
        should("test dateStart") {
            // uncomment below to test the property
            //modelInstance.dateStart shouldBe ("TODO")
        }

        // to test the property `dateEnd`
        should("test dateEnd") {
            // uncomment below to test the property
            //modelInstance.dateEnd shouldBe ("TODO")
        }

        // to test the property `usageCount`
        should("test usageCount") {
            // uncomment below to test the property
            //modelInstance.usageCount shouldBe ("TODO")
        }

        // to test the property `conditions`
        should("test conditions") {
            // uncomment below to test the property
            //modelInstance.conditions shouldBe ("TODO")
        }

        // to test the property `usesPerOrderLimit`
        should("test usesPerOrderLimit") {
            // uncomment below to test the property
            //modelInstance.usesPerOrderLimit shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
