/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CategoryFind200ResponseResult
import org.openapitools.client.models.CategoryFind200ResponseResultCategoryInner

class CategoryFind200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryFind200ResponseResult
        //val modelInstance = CategoryFind200ResponseResult()

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

    }
}
