/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CategoryAddBatchPayloadInner
import org.openapitools.client.models.CategoryAddBatchPayloadInnerImagesInner

class CategoryAddBatchPayloadInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryAddBatchPayloadInner
        //val modelInstance = CategoryAddBatchPayloadInner()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `avail`
        should("test avail") {
            // uncomment below to test the property
            //modelInstance.avail shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `metaTitle`
        should("test metaTitle") {
            // uncomment below to test the property
            //modelInstance.metaTitle shouldBe ("TODO")
        }

        // to test the property `metaDescription`
        should("test metaDescription") {
            // uncomment below to test the property
            //modelInstance.metaDescription shouldBe ("TODO")
        }

        // to test the property `metaKeywords`
        should("test metaKeywords") {
            // uncomment below to test the property
            //modelInstance.metaKeywords shouldBe ("TODO")
        }

        // to test the property `parentId`
        should("test parentId") {
            // uncomment below to test the property
            //modelInstance.parentId shouldBe ("TODO")
        }

        // to test the property `sortOrder`
        should("test sortOrder") {
            // uncomment below to test the property
            //modelInstance.sortOrder shouldBe ("TODO")
        }

        // to test the property `seoUrl`
        should("test seoUrl") {
            // uncomment below to test the property
            //modelInstance.seoUrl shouldBe ("TODO")
        }

        // to test the property `storeId`
        should("test storeId") {
            // uncomment below to test the property
            //modelInstance.storeId shouldBe ("TODO")
        }

        // to test the property `images`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `storesIds`
        should("test storesIds") {
            // uncomment below to test the property
            //modelInstance.storesIds shouldBe ("TODO")
        }

    }
}
