/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CustomerAddress
import org.openapitools.client.models.Country
import org.openapitools.client.models.State

class CustomerAddressTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerAddress
        //val modelInstance = CustomerAddress()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `firstName`
        should("test firstName") {
            // uncomment below to test the property
            //modelInstance.firstName shouldBe ("TODO")
        }

        // to test the property `lastName`
        should("test lastName") {
            // uncomment below to test the property
            //modelInstance.lastName shouldBe ("TODO")
        }

        // to test the property `postcode`
        should("test postcode") {
            // uncomment below to test the property
            //modelInstance.postcode shouldBe ("TODO")
        }

        // to test the property `address1`
        should("test address1") {
            // uncomment below to test the property
            //modelInstance.address1 shouldBe ("TODO")
        }

        // to test the property `address2`
        should("test address2") {
            // uncomment below to test the property
            //modelInstance.address2 shouldBe ("TODO")
        }

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `phoneMobile`
        should("test phoneMobile") {
            // uncomment below to test the property
            //modelInstance.phoneMobile shouldBe ("TODO")
        }

        // to test the property `city`
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `company`
        should("test company") {
            // uncomment below to test the property
            //modelInstance.company shouldBe ("TODO")
        }

        // to test the property `fax`
        should("test fax") {
            // uncomment below to test the property
            //modelInstance.fax shouldBe ("TODO")
        }

        // to test the property `website`
        should("test website") {
            // uncomment below to test the property
            //modelInstance.website shouldBe ("TODO")
        }

        // to test the property `gender`
        should("test gender") {
            // uncomment below to test the property
            //modelInstance.gender shouldBe ("TODO")
        }

        // to test the property `region`
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

        // to test the property `default`
        should("test default") {
            // uncomment below to test the property
            //modelInstance.default shouldBe ("TODO")
        }

        // to test the property `taxId`
        should("test taxId") {
            // uncomment below to test the property
            //modelInstance.taxId shouldBe ("TODO")
        }

        // to test the property `identificationNumber`
        should("test identificationNumber") {
            // uncomment below to test the property
            //modelInstance.identificationNumber shouldBe ("TODO")
        }

        // to test the property `alias`
        should("test alias") {
            // uncomment below to test the property
            //modelInstance.alias shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
