/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CustomerDelete200ResponseResult

class CustomerDelete200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerDelete200ResponseResult
        //val modelInstance = CustomerDelete200ResponseResult()

        // to test the property `deleteItems`
        should("test deleteItems") {
            // uncomment below to test the property
            //modelInstance.deleteItems shouldBe ("TODO")
        }

    }
}
