/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CustomerGroupAdd200ResponseResult

class CustomerGroupAdd200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerGroupAdd200ResponseResult
        //val modelInstance = CustomerGroupAdd200ResponseResult()

        // to test the property `groupId`
        should("test groupId") {
            // uncomment below to test the property
            //modelInstance.groupId shouldBe ("TODO")
        }

    }
}
