/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CustomerAddressAdd

class CustomerAddressAddTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerAddressAdd
        //val modelInstance = CustomerAddressAdd()

        // to test the property `customerId` - Defines customer id
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `address1` - Specifies customer's address address1
        should("test address1") {
            // uncomment below to test the property
            //modelInstance.address1 shouldBe ("TODO")
        }

        // to test the property `city` - Specifies customer's address city
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `country` - Specifies customer's address ISO code or name of country
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `postcode` - Specifies customer's address postcode
        should("test postcode") {
            // uncomment below to test the property
            //modelInstance.postcode shouldBe ("TODO")
        }

        // to test the property `storeId` - Store Id
        should("test storeId") {
            // uncomment below to test the property
            //modelInstance.storeId shouldBe ("TODO")
        }

        // to test the property `firstName` - Defines customer's address first name
        should("test firstName") {
            // uncomment below to test the property
            //modelInstance.firstName shouldBe ("TODO")
        }

        // to test the property `lastName` - Defines customer's address last name
        should("test lastName") {
            // uncomment below to test the property
            //modelInstance.lastName shouldBe ("TODO")
        }

        // to test the property `company` - Defines customer's address company
        should("test company") {
            // uncomment below to test the property
            //modelInstance.company shouldBe ("TODO")
        }

        // to test the property `address2` - Specifies customer's address address2
        should("test address2") {
            // uncomment below to test the property
            //modelInstance.address2 shouldBe ("TODO")
        }

        // to test the property `state` - Specifies customer's address ISO code or name of state
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `identificationNumber` - Specifies the national ID card number of this person, or a unique tax identification number for customer's address
        should("test identificationNumber") {
            // uncomment below to test the property
            //modelInstance.identificationNumber shouldBe ("TODO")
        }

        // to test the property `types` - Specifies customer's address types
        should("test types") {
            // uncomment below to test the property
            //modelInstance.types shouldBe ("TODO")
        }

        // to test the property `default` - Specifies whether the customer's address is used by default
        should("test default") {
            // uncomment below to test the property
            //modelInstance.default shouldBe ("TODO")
        }

        // to test the property `phone` - Defines customer's address phone number
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `phoneMobile` - Defines customer's address mobile phone number
        should("test phoneMobile") {
            // uncomment below to test the property
            //modelInstance.phoneMobile shouldBe ("TODO")
        }

        // to test the property `fax` - Defines customer's address fax
        should("test fax") {
            // uncomment below to test the property
            //modelInstance.fax shouldBe ("TODO")
        }

        // to test the property `website` - Defines Link to customer's address website
        should("test website") {
            // uncomment below to test the property
            //modelInstance.website shouldBe ("TODO")
        }

        // to test the property `gender` - Defines customer's address gender
        should("test gender") {
            // uncomment below to test the property
            //modelInstance.gender shouldBe ("TODO")
        }

        // to test the property `taxId` - Add Tax Id
        should("test taxId") {
            // uncomment below to test the property
            //modelInstance.taxId shouldBe ("TODO")
        }

        // to test the property `alias` - Specifies customer's alias in the address book
        should("test alias") {
            // uncomment below to test the property
            //modelInstance.alias shouldBe ("TODO")
        }

    }
}
