/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CustomerAttributeValue

class CustomerAttributeValueTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerAttributeValue
        //val modelInstance = CustomerAttributeValue()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
