/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderShipmentAdd200ResponseResult

class OrderShipmentAdd200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderShipmentAdd200ResponseResult
        //val modelInstance = OrderShipmentAdd200ResponseResult()

        // to test the property `shipmentId`
        should("test shipmentId") {
            // uncomment below to test the property
            //modelInstance.shipmentId shouldBe ("TODO")
        }

    }
}
