/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Order
import org.openapitools.client.models.A2CDateTime
import org.openapitools.client.models.BaseCustomer
import org.openapitools.client.models.Currency
import org.openapitools.client.models.CustomerAddress
import org.openapitools.client.models.OrderItem
import org.openapitools.client.models.OrderPaymentMethod
import org.openapitools.client.models.OrderRefund
import org.openapitools.client.models.OrderShippingMethod
import org.openapitools.client.models.OrderStatus
import org.openapitools.client.models.OrderTotal
import org.openapitools.client.models.OrderTotals
import org.openapitools.client.models.OrderTotalsNewDiscount

class OrderTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Order
        //val modelInstance = Order()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `orderId`
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `basketId`
        should("test basketId") {
            // uncomment below to test the property
            //modelInstance.basketId shouldBe ("TODO")
        }

        // to test the property `channelId`
        should("test channelId") {
            // uncomment below to test the property
            //modelInstance.channelId shouldBe ("TODO")
        }

        // to test the property `customer`
        should("test customer") {
            // uncomment below to test the property
            //modelInstance.customer shouldBe ("TODO")
        }

        // to test the property `createAt`
        should("test createAt") {
            // uncomment below to test the property
            //modelInstance.createAt shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `shippingAddress`
        should("test shippingAddress") {
            // uncomment below to test the property
            //modelInstance.shippingAddress shouldBe ("TODO")
        }

        // to test the property `billingAddress`
        should("test billingAddress") {
            // uncomment below to test the property
            //modelInstance.billingAddress shouldBe ("TODO")
        }

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `shippingMethod`
        should("test shippingMethod") {
            // uncomment below to test the property
            //modelInstance.shippingMethod shouldBe ("TODO")
        }

        // to test the property `shippingMethods`
        should("test shippingMethods") {
            // uncomment below to test the property
            //modelInstance.shippingMethods shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `totals`
        should("test totals") {
            // uncomment below to test the property
            //modelInstance.totals shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `discounts`
        should("test discounts") {
            // uncomment below to test the property
            //modelInstance.discounts shouldBe ("TODO")
        }

        // to test the property `orderProducts`
        should("test orderProducts") {
            // uncomment below to test the property
            //modelInstance.orderProducts shouldBe ("TODO")
        }

        // to test the property `bundles`
        should("test bundles") {
            // uncomment below to test the property
            //modelInstance.bundles shouldBe ("TODO")
        }

        // to test the property `modifiedAt`
        should("test modifiedAt") {
            // uncomment below to test the property
            //modelInstance.modifiedAt shouldBe ("TODO")
        }

        // to test the property `finishedTime`
        should("test finishedTime") {
            // uncomment below to test the property
            //modelInstance.finishedTime shouldBe ("TODO")
        }

        // to test the property `comment`
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `storeId`
        should("test storeId") {
            // uncomment below to test the property
            //modelInstance.storeId shouldBe ("TODO")
        }

        // to test the property `warehousesIds`
        should("test warehousesIds") {
            // uncomment below to test the property
            //modelInstance.warehousesIds shouldBe ("TODO")
        }

        // to test the property `refunds`
        should("test refunds") {
            // uncomment below to test the property
            //modelInstance.refunds shouldBe ("TODO")
        }

        // to test the property `giftMessage`
        should("test giftMessage") {
            // uncomment below to test the property
            //modelInstance.giftMessage shouldBe ("TODO")
        }

        // to test the property `orderDetailsUrl`
        should("test orderDetailsUrl") {
            // uncomment below to test the property
            //modelInstance.orderDetailsUrl shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
