/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderRefundAddItemsInner

class OrderRefundAddItemsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderRefundAddItemsInner
        //val modelInstance = OrderRefundAddItemsInner()

        // to test the property `orderProductId`
        should("test orderProductId") {
            // uncomment below to test the property
            //modelInstance.orderProductId shouldBe ("TODO")
        }

        // to test the property `quantity`
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

    }
}
