/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderTotal

class OrderTotalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderTotal
        //val modelInstance = OrderTotal()

        // to test the property `subtotalExTax`
        should("test subtotalExTax") {
            // uncomment below to test the property
            //modelInstance.subtotalExTax shouldBe ("TODO")
        }

        // to test the property `wrappingExTax`
        should("test wrappingExTax") {
            // uncomment below to test the property
            //modelInstance.wrappingExTax shouldBe ("TODO")
        }

        // to test the property `shippingExTax`
        should("test shippingExTax") {
            // uncomment below to test the property
            //modelInstance.shippingExTax shouldBe ("TODO")
        }

        // to test the property `totalDiscount`
        should("test totalDiscount") {
            // uncomment below to test the property
            //modelInstance.totalDiscount shouldBe ("TODO")
        }

        // to test the property `totalTax`
        should("test totalTax") {
            // uncomment below to test the property
            //modelInstance.totalTax shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `totalPaid`
        should("test totalPaid") {
            // uncomment below to test the property
            //modelInstance.totalPaid shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
