/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderShipmentAddBatchPayloadInner
import org.openapitools.client.models.OrderShipmentAddBatchPayloadInnerItemsInner

class OrderShipmentAddBatchPayloadInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderShipmentAddBatchPayloadInner
        //val modelInstance = OrderShipmentAddBatchPayloadInner()

        // to test the property `orderId`
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `trackingNumber`
        should("test trackingNumber") {
            // uncomment below to test the property
            //modelInstance.trackingNumber shouldBe ("TODO")
        }

        // to test the property `storeId`
        should("test storeId") {
            // uncomment below to test the property
            //modelInstance.storeId shouldBe ("TODO")
        }

        // to test the property `warehouseId`
        should("test warehouseId") {
            // uncomment below to test the property
            //modelInstance.warehouseId shouldBe ("TODO")
        }

        // to test the property `carrierId`
        should("test carrierId") {
            // uncomment below to test the property
            //modelInstance.carrierId shouldBe ("TODO")
        }

        // to test the property `carrierName`
        should("test carrierName") {
            // uncomment below to test the property
            //modelInstance.carrierName shouldBe ("TODO")
        }

        // to test the property `trackingLink`
        should("test trackingLink") {
            // uncomment below to test the property
            //modelInstance.trackingLink shouldBe ("TODO")
        }

        // to test the property `shipmentProvider`
        should("test shipmentProvider") {
            // uncomment below to test the property
            //modelInstance.shipmentProvider shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `sendNotifications`
        should("test sendNotifications") {
            // uncomment below to test the property
            //modelInstance.sendNotifications shouldBe ("TODO")
        }

    }
}
