/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderAddOrderItemInnerOrderItemOptionInner

class OrderAddOrderItemInnerOrderItemOptionInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderAddOrderItemInnerOrderItemOptionInner
        //val modelInstance = OrderAddOrderItemInnerOrderItemOptionInner()

        // to test the property `orderItemOptionName` - Ordered Product Option Name. Where x is order item ID, y is order item option ID
        should("test orderItemOptionName") {
            // uncomment below to test the property
            //modelInstance.orderItemOptionName shouldBe ("TODO")
        }

        // to test the property `orderItemOptionValue` - Ordered product option value Where x is order item ID, y - order item option ID
        should("test orderItemOptionValue") {
            // uncomment below to test the property
            //modelInstance.orderItemOptionValue shouldBe ("TODO")
        }

        // to test the property `orderItemOptionPrice` - Ordered product option price Where x is order item ID, y - order item option ID
        should("test orderItemOptionPrice") {
            // uncomment below to test the property
            //modelInstance.orderItemOptionPrice shouldBe ("TODO")
        }

    }
}
