/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner

class OrderPreestimateShippingListOrderItemInnerOrderItemOptionInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner
        //val modelInstance = OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner()

        // to test the property `orderItemOptionName` - Ordered Product Option Name. Where x is order item ID, y is order item option ID
        should("test orderItemOptionName") {
            // uncomment below to test the property
            //modelInstance.orderItemOptionName shouldBe ("TODO")
        }

        // to test the property `orderItemOptionId` - Product Option ID. Where x is order item ID, y is order item option ID
        should("test orderItemOptionId") {
            // uncomment below to test the property
            //modelInstance.orderItemOptionId shouldBe ("TODO")
        }

        // to test the property `orderItemOptionValue` - Ordered product option value Where x is order item ID, y - order item option ID
        should("test orderItemOptionValue") {
            // uncomment below to test the property
            //modelInstance.orderItemOptionValue shouldBe ("TODO")
        }

        // to test the property `orderItemOptionValueId` - Product option value ID, where x is order item ID, y - order item option ID
        should("test orderItemOptionValueId") {
            // uncomment below to test the property
            //modelInstance.orderItemOptionValueId shouldBe ("TODO")
        }

        // to test the property `orderItemOptionUsedInCombinations` - Product option used in combinations flag, where x is order item ID, y - order item option ID
        should("test orderItemOptionUsedInCombinations") {
            // uncomment below to test the property
            //modelInstance.orderItemOptionUsedInCombinations shouldBe ("TODO")
        }

    }
}
