/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.OrderCalculateOrderItemInner
import org.openapitools.client.models.OrderCalculateOrderItemInnerOrderItemOptionInner

class OrderCalculateOrderItemInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderCalculateOrderItemInner
        //val modelInstance = OrderCalculateOrderItemInner()

        // to test the property `orderItemId` - Defines orders specified by order item id
        should("test orderItemId") {
            // uncomment below to test the property
            //modelInstance.orderItemId shouldBe ("TODO")
        }

        // to test the property `orderItemQuantity` - Defines orders specified by order item quantity
        should("test orderItemQuantity") {
            // uncomment below to test the property
            //modelInstance.orderItemQuantity shouldBe ("TODO")
        }

        // to test the property `orderItemVariantId` - Ordered product variant. Where x is order item ID
        should("test orderItemVariantId") {
            // uncomment below to test the property
            //modelInstance.orderItemVariantId shouldBe ("TODO")
        }

        // to test the property `orderItemParent` - Index of the parent grouped/bundle product
        should("test orderItemParent") {
            // uncomment below to test the property
            //modelInstance.orderItemParent shouldBe ("TODO")
        }

        // to test the property `orderItemParentOptionName` - Option name of the parent grouped/bundle product
        should("test orderItemParentOptionName") {
            // uncomment below to test the property
            //modelInstance.orderItemParentOptionName shouldBe ("TODO")
        }

        // to test the property `orderItemOption`
        should("test orderItemOption") {
            // uncomment below to test the property
            //modelInstance.orderItemOption shouldBe ("TODO")
        }

    }
}
