/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProductVariantDeleteBatch
import org.openapitools.client.models.ProductVariantDeleteBatchPayloadInner

class ProductVariantDeleteBatchTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductVariantDeleteBatch
        //val modelInstance = ProductVariantDeleteBatch()

        // to test the property `payload` - Contains an array of product variant deletion requests, each including the product ID and variant ID. The list of properties may vary depending on the specific platform.
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

        // to test the property `clearCache`
        should("test clearCache") {
            // uncomment below to test the property
            //modelInstance.clearCache shouldBe ("TODO")
        }

        // to test the property `reindex`
        should("test reindex") {
            // uncomment below to test the property
            //modelInstance.reindex shouldBe ("TODO")
        }

    }
}
