/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProductCurrencyAdd200ResponseResult

class ProductCurrencyAdd200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductCurrencyAdd200ResponseResult
        //val modelInstance = ProductCurrencyAdd200ResponseResult()

        // to test the property `currencyId`
        should("test currencyId") {
            // uncomment below to test the property
            //modelInstance.currencyId shouldBe ("TODO")
        }

    }
}
