/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProductOptionAssign200ResponseResult

class ProductOptionAssign200ResponseResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductOptionAssign200ResponseResult
        //val modelInstance = ProductOptionAssign200ResponseResult()

        // to test the property `productOptionId`
        should("test productOptionId") {
            // uncomment below to test the property
            //modelInstance.productOptionId shouldBe ("TODO")
        }

    }
}
