/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ResponseAttributeListResult
import org.openapitools.client.models.StoreAttribute

class ResponseAttributeListResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseAttributeListResult
        //val modelInstance = ResponseAttributeListResult()

        // to test the property `attributesCount`
        should("test attributesCount") {
            // uncomment below to test the property
            //modelInstance.attributesCount shouldBe ("TODO")
        }

        // to test the property `attribute`
        should("test attribute") {
            // uncomment below to test the property
            //modelInstance.attribute shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
