/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ResponseCartCouponListResult
import org.openapitools.client.models.Coupon

class ResponseCartCouponListResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseCartCouponListResult
        //val modelInstance = ResponseCartCouponListResult()

        // to test the property `couponCount`
        should("test couponCount") {
            // uncomment below to test the property
            //modelInstance.couponCount shouldBe ("TODO")
        }

        // to test the property `coupon`
        should("test coupon") {
            // uncomment below to test the property
            //modelInstance.coupon shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
