/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ResponseCartCatalogPriceRulesListResult
import org.openapitools.client.models.CatalogPriceRule

class ResponseCartCatalogPriceRulesListResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseCartCatalogPriceRulesListResult
        //val modelInstance = ResponseCartCatalogPriceRulesListResult()

        // to test the property `catalogPriceRulesCount`
        should("test catalogPriceRulesCount") {
            // uncomment below to test the property
            //modelInstance.catalogPriceRulesCount shouldBe ("TODO")
        }

        // to test the property `catalogPriceRules`
        should("test catalogPriceRules") {
            // uncomment below to test the property
            //modelInstance.catalogPriceRules shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
