/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ResponseAttributeAttributesetListResult
import org.openapitools.client.models.StoreAttributeAttributeSet

class ResponseAttributeAttributesetListResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseAttributeAttributesetListResult
        //val modelInstance = ResponseAttributeAttributesetListResult()

        // to test the property `attributeSet`
        should("test attributeSet") {
            // uncomment below to test the property
            //modelInstance.attributeSet shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
