/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ResponseProductCurrencyListResult
import org.openapitools.client.models.Currency

class ResponseProductCurrencyListResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseProductCurrencyListResult
        //val modelInstance = ResponseProductCurrencyListResult()

        // to test the property `totalCount`
        should("test totalCount") {
            // uncomment below to test the property
            //modelInstance.totalCount shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `additionalFields`
        should("test additionalFields") {
            // uncomment below to test the property
            //modelInstance.additionalFields shouldBe ("TODO")
        }

        // to test the property `customFields`
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

    }
}
