/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReturnInfo200Response
import org.openapitools.client.models.Return

class ReturnInfo200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReturnInfo200Response
        //val modelInstance = ReturnInfo200Response()

        // to test the property `returnCode`
        should("test returnCode") {
            // uncomment below to test the property
            //modelInstance.returnCode shouldBe ("TODO")
        }

        // to test the property `returnMessage`
        should("test returnMessage") {
            // uncomment below to test the property
            //modelInstance.returnMessage shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

    }
}
