/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ReturnApi
import org.openapitools.client.models.ModelResponseReturnList
import org.openapitools.client.models.ReturnActionList200Response
import org.openapitools.client.models.ReturnCount200Response
import org.openapitools.client.models.ReturnInfo200Response
import org.openapitools.client.models.ReturnReasonList200Response
import org.openapitools.client.models.ReturnStatusList200Response

class ReturnApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReturnApi
        //val apiInstance = ReturnApi()

        // to test returnActionList
        should("test returnActionList") {
            // uncomment below to test returnActionList
            //val result : ReturnActionList200Response = apiInstance.returnActionList()
            //result shouldBe ("TODO")
        }

        // to test returnCount
        should("test returnCount") {
            // uncomment below to test returnCount
            //val orderIds : kotlin.String = 24,25 // kotlin.String | Counts return requests specified by order ids
            //val customerId : kotlin.String = 5 // kotlin.String | Counts return requests quantity specified by customer id
            //val storeId : kotlin.String = 1 // kotlin.String | Store Id
            //val status : kotlin.String = disabled // kotlin.String | Defines status
            //val returnType : kotlin.String = FBA // kotlin.String | Retrieves returns specified by return type
            //val createdFrom : kotlin.String = 2010-07-29 13:45:52 // kotlin.String | Retrieve entities from their creation date
            //val createdTo : kotlin.String = 2100-08-29 13:45:52 // kotlin.String | Retrieve entities to their creation date
            //val modifiedFrom : kotlin.String = 2010-07-29 13:45:52 // kotlin.String | Retrieve entities from their modification date
            //val modifiedTo : kotlin.String = 2100-08-29 13:45:52 // kotlin.String | Retrieve entities to their modification date
            //val reportRequestId : kotlin.String = 105245017661 // kotlin.String | Report request id
            //val disableReportCache : kotlin.Boolean = false // kotlin.Boolean | Disable report cache for current request
            //val result : ReturnCount200Response = apiInstance.returnCount(orderIds, customerId, storeId, status, returnType, createdFrom, createdTo, modifiedFrom, modifiedTo, reportRequestId, disableReportCache)
            //result shouldBe ("TODO")
        }

        // to test returnInfo
        should("test returnInfo") {
            // uncomment below to test returnInfo
            //val id : kotlin.String = 10 // kotlin.String | Entity id
            //val orderId : kotlin.String = 25 // kotlin.String | Defines the order id
            //val storeId : kotlin.String = 1 // kotlin.String | Store Id
            //val params : kotlin.String = id,order_products // kotlin.String | Set this parameter in order to choose which entity fields you want to retrieve
            //val exclude : kotlin.String = id,order_id // kotlin.String | Set this parameter in order to choose which entity fields you want to ignore. Works only if parameter `params` equal force_all
            //val responseFields : kotlin.String = {return_code,return_message,result} // kotlin.String | Set this parameter in order to choose which entity fields you want to retrieve
            //val result : ReturnInfo200Response = apiInstance.returnInfo(id, orderId, storeId, params, exclude, responseFields)
            //result shouldBe ("TODO")
        }

        // to test returnList
        should("test returnList") {
            // uncomment below to test returnList
            //val start : kotlin.Int = 0 // kotlin.Int | This parameter sets the number from which you want to get entities
            //val count : kotlin.Int = 20 // kotlin.Int | This parameter sets the entity amount that has to be retrieved. Max allowed count=250
            //val pageCursor : kotlin.String =  // kotlin.String | Used to retrieve entities via cursor-based pagination (it can't be used with any other filtering parameter)
            //val params : kotlin.String = id,order_products // kotlin.String | Set this parameter in order to choose which entity fields you want to retrieve
            //val exclude : kotlin.String = id,order_id // kotlin.String | Set this parameter in order to choose which entity fields you want to ignore. Works only if parameter `params` equal force_all
            //val responseFields : kotlin.String = {return_code,return_message,pagination,result} // kotlin.String | Set this parameter in order to choose which entity fields you want to retrieve
            //val orderId : kotlin.String = 25 // kotlin.String | Defines the order id
            //val orderIds : kotlin.String = 24,25 // kotlin.String | Retrieves return requests specified by order ids
            //val customerId : kotlin.String = 5 // kotlin.String | Retrieves return requests specified by customer id
            //val storeId : kotlin.String = 1 // kotlin.String | Store Id
            //val status : kotlin.String = disabled // kotlin.String | Defines status
            //val returnType : kotlin.String = FBA // kotlin.String | Retrieves returns specified by return type
            //val createdFrom : kotlin.String = 2010-07-29 13:45:52 // kotlin.String | Retrieve entities from their creation date
            //val createdTo : kotlin.String = 2100-08-29 13:45:52 // kotlin.String | Retrieve entities to their creation date
            //val modifiedFrom : kotlin.String = 2010-07-29 13:45:52 // kotlin.String | Retrieve entities from their modification date
            //val modifiedTo : kotlin.String = 2100-08-29 13:45:52 // kotlin.String | Retrieve entities to their modification date
            //val reportRequestId : kotlin.String = 105245017661 // kotlin.String | Report request id
            //val disableReportCache : kotlin.Boolean = false // kotlin.Boolean | Disable report cache for current request
            //val result : ModelResponseReturnList = apiInstance.returnList(start, count, pageCursor, params, exclude, responseFields, orderId, orderIds, customerId, storeId, status, returnType, createdFrom, createdTo, modifiedFrom, modifiedTo, reportRequestId, disableReportCache)
            //result shouldBe ("TODO")
        }

        // to test returnReasonList
        should("test returnReasonList") {
            // uncomment below to test returnReasonList
            //val storeId : kotlin.String = 1 // kotlin.String | Store Id
            //val result : ReturnReasonList200Response = apiInstance.returnReasonList(storeId)
            //result shouldBe ("TODO")
        }

        // to test returnStatusList
        should("test returnStatusList") {
            // uncomment below to test returnStatusList
            //val result : ReturnStatusList200Response = apiInstance.returnStatusList()
            //result shouldBe ("TODO")
        }

    }
}
