/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Image

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param createdTime 
 * @param modifiedTime 
 * @param fullDescription 
 * @param shortDescription 
 * @param storesIds 
 * @param active 
 * @param url 
 * @param metaTitle 
 * @param metaKeywords 
 * @param metaDescription 
 * @param images 
 * @param additionalFields 
 * @param customFields 
 */


data class Brand (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "created_time")
    val createdTime: kotlin.String? = null,

    @Json(name = "modified_time")
    val modifiedTime: kotlin.String? = null,

    @Json(name = "full_description")
    val fullDescription: kotlin.String? = null,

    @Json(name = "short_description")
    val shortDescription: kotlin.String? = null,

    @Json(name = "stores_ids")
    val storesIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "active")
    val active: kotlin.Boolean? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "meta_title")
    val metaTitle: kotlin.String? = null,

    @Json(name = "meta_keywords")
    val metaKeywords: kotlin.String? = null,

    @Json(name = "meta_description")
    val metaDescription: kotlin.String? = null,

    @Json(name = "images")
    val images: kotlin.collections.List<Image>? = null,

    @Json(name = "additional_fields")
    val additionalFields: kotlin.Any? = null,

    @Json(name = "custom_fields")
    val customFields: kotlin.Any? = null

) {


}

