/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PluginList

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param allPlugins 
 * @param plugins 
 */


data class CartPluginList200ResponseResult (

    @Json(name = "all_plugins")
    val allPlugins: kotlin.Int? = null,

    @Json(name = "plugins")
    val plugins: kotlin.collections.List<PluginList>? = null

) {


}

