/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CustomerAddress

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param avail 
 * @param address 
 * @param carriersIds 
 * @param storesIds 
 * @param additionalFields 
 * @param customFields 
 */


data class CartWarehouse (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "avail")
    val avail: kotlin.Boolean? = null,

    @Json(name = "address")
    val address: CustomerAddress? = null,

    @Json(name = "carriers_ids")
    val carriersIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "stores_ids")
    val storesIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "additional_fields")
    val additionalFields: kotlin.Any? = null,

    @Json(name = "custom_fields")
    val customFields: kotlin.Any? = null

) {


}

