/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url 
 * @param imageName 
 * @param type 
 * @param label 
 */


data class CategoryAddBatchPayloadInnerImagesInner (

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "image_name")
    val imageName: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "label")
    val label: kotlin.String? = null

) {


}

