/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param owner 
 * @param country 
 * @param state 
 * @param stateCode 
 * @param city 
 * @param streetAddress 
 * @param streetAddressLine2 
 * @param zipCode 
 * @param email 
 * @param phone 
 * @param additionalFields 
 * @param customFields 
 */


data class Info (

    @Json(name = "owner")
    val owner: kotlin.String? = null,

    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.String? = null,

    @Json(name = "state_code")
    val stateCode: kotlin.String? = null,

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "street_address")
    val streetAddress: kotlin.String? = null,

    @Json(name = "street_address_line_2")
    val streetAddressLine2: kotlin.String? = null,

    @Json(name = "zip_code")
    val zipCode: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "phone")
    val phone: kotlin.String? = null,

    @Json(name = "additional_fields")
    val additionalFields: kotlin.Any? = null,

    @Json(name = "custom_fields")
    val customFields: kotlin.Any? = null

) {


}

