/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderReturnUpdateOrderProductsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param returnId Return ID
 * @param orderProducts 
 * @param orderId Defines the order id
 * @param storeId Store Id
 * @param itemRestock Boolean, whether or not to add the line items back to the store inventory.
 * @param returnStatusId Defines return request status
 * @param staffNote Specifies staff note
 * @param comment Specifies return comment
 * @param sendNotifications Send notifications to customer after order was created
 * @param rejectReason Defines return reject reason
 */


data class OrderReturnUpdate (

    /* Return ID */
    @Json(name = "return_id")
    val returnId: kotlin.String,

    @Json(name = "order_products")
    val orderProducts: kotlin.collections.List<OrderReturnUpdateOrderProductsInner>,

    /* Defines the order id */
    @Json(name = "order_id")
    val orderId: kotlin.String? = null,

    /* Store Id */
    @Json(name = "store_id")
    val storeId: kotlin.String? = null,

    /* Boolean, whether or not to add the line items back to the store inventory. */
    @Json(name = "item_restock")
    val itemRestock: kotlin.Boolean? = false,

    /* Defines return request status */
    @Json(name = "return_status_id")
    val returnStatusId: kotlin.String? = null,

    /* Specifies staff note */
    @Json(name = "staff_note")
    val staffNote: kotlin.String? = null,

    /* Specifies return comment */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Send notifications to customer after order was created */
    @Json(name = "send_notifications")
    val sendNotifications: kotlin.Boolean? = false,

    /* Defines return reject reason */
    @Json(name = "reject_reason")
    val rejectReason: kotlin.String? = null

) {


}

