/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param refundId 
 * @param additionalRefundIds 
 */


data class OrderRefundAdd200ResponseResult (

    @Json(name = "refund_id")
    val refundId: kotlin.String? = null,

    @Json(name = "additional_refund_ids")
    val additionalRefundIds: kotlin.String? = null

) {


}

