/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * If the seller is subscribed to \"Business Policies\", use the seller_profiles instead of the shipping_details, payment_methods and return_accepted params.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">seller_profiles[<b>shipping_profile_id</b>] = string</br>seller_profiles[<b>payment_profile_id</b>] = string</br>seller_profiles[<b>return_profile_id</b>] = string</br></code></div></div>
 *
 * @param shippingProfileId 
 * @param paymentProfileId 
 * @param returnProfileId 
 */


data class ProductAddSellerProfiles (

    @Json(name = "shipping_profile_id")
    val shippingProfileId: kotlin.String? = null,

    @Json(name = "payment_profile_id")
    val paymentProfileId: kotlin.String? = null,

    @Json(name = "return_profile_id")
    val returnProfileId: kotlin.String? = null

) {


}

