/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param warehouseId 
 * @param quantity 
 * @param inStock 
 * @param priority 
 * @param additionalFields 
 * @param customFields 
 */


data class ProductInventory (

    @Json(name = "warehouse_id")
    val warehouseId: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal? = null,

    @Json(name = "in_stock")
    val inStock: kotlin.Boolean? = null,

    @Json(name = "priority")
    val priority: kotlin.Int? = null,

    @Json(name = "additional_fields")
    val additionalFields: kotlin.Any? = null,

    @Json(name = "custom_fields")
    val customFields: kotlin.Any? = null

) {


}

