/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The price at which Best Offers are automatically accepted.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">best_offer[<b>minimum_offer_price</b>] = decimal</br>best_offer[<b>auto_accept_price</b>] = decimal</br></code></div></div>
 *
 * @param minimumOfferPrice 
 * @param autoAcceptPrice 
 */


data class ProductAddBestOffer (

    @Json(name = "minimum_offer_price")
    val minimumOfferPrice: java.math.BigDecimal? = null,

    @Json(name = "auto_accept_price")
    val autoAcceptPrice: java.math.BigDecimal? = null

) {


}

