/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param productOptionItemId 
 * @param name 
 * @param sortOrder 
 * @param price 
 * @param weight 
 * @param quantity 
 * @param typePrice 
 * @param sku 
 * @param isDefault 
 * @param additionalFields 
 * @param customFields 
 */


data class ProductOptionItem (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "product_option_item_id")
    val productOptionItemId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "sort_order")
    val sortOrder: kotlin.Int? = null,

    @Json(name = "price")
    val price: kotlin.String? = null,

    @Json(name = "weight")
    val weight: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,

    @Json(name = "type_price")
    val typePrice: kotlin.String? = null,

    @Json(name = "sku")
    val sku: kotlin.String? = null,

    @Json(name = "is_default")
    val isDefault: kotlin.Boolean? = null,

    @Json(name = "additional_fields")
    val additionalFields: kotlin.Any? = null,

    @Json(name = "custom_fields")
    val customFields: kotlin.Any? = null

) {


}

