/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProductPriceUpdateGroupPricesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId Defines the product where the price has to be updated
 * @param groupPrices Defines product's group prices
 */


data class ProductPriceUpdate (

    /* Defines the product where the price has to be updated */
    @Json(name = "product_id")
    val productId: kotlin.String? = null,

    /* Defines product's group prices */
    @Json(name = "group_prices")
    val groupPrices: kotlin.collections.List<ProductPriceUpdateGroupPricesInner>? = null

) {


}

