/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Defines personalization settings for the listing. To enable personalization, is_personalizable must be set to true. When enabled, additional fields may be used to configure the personalization experience, including whether it is required (personalization_is_required), the maximum character limit (personalization_char_count_max), and buyer instructions (personalization_instructions). All related fields are only applicable if personalization is enabled.
 *
 * @param isPersonalizable 
 * @param personalizationIsRequired 
 * @param personalizationCharCountMax 
 * @param personalizationInstructions 
 */


data class ProductAddPersonalizationDetails (

    @Json(name = "is_personalizable")
    val isPersonalizable: kotlin.Boolean,

    @Json(name = "personalization_is_required")
    val personalizationIsRequired: kotlin.Boolean? = null,

    @Json(name = "personalization_char_count_max")
    val personalizationCharCountMax: kotlin.Int? = null,

    @Json(name = "personalization_instructions")
    val personalizationInstructions: kotlin.String? = null

) {


}

