/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param optionName 
 * @param optionValueName 
 */


data class ProductVariantAddBatchPayloadInnerCombinationInner (

    @Json(name = "option_name")
    val optionName: kotlin.String,

    @Json(name = "option_value_name")
    val optionValueName: kotlin.String

) {


}

