/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProductAddGroupPricesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId Defines the product to which the price has to be added
 * @param groupPrices Defines product's group prices
 * @param storeId Store Id
 */


data class ProductPriceAdd (

    /* Defines the product to which the price has to be added */
    @Json(name = "product_id")
    val productId: kotlin.String? = null,

    /* Defines product's group prices */
    @Json(name = "group_prices")
    val groupPrices: kotlin.collections.List<ProductAddGroupPricesInner>? = null,

    /* Store Id */
    @Json(name = "store_id")
    val storeId: kotlin.String? = null

) {


}

