/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.A2CDateTime

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param src 
 * @param scope 
 * @param event 
 * @param loadMethod 
 * @param html 
 * @param createdTime 
 * @param modifiedTime 
 * @param additionalFields 
 * @param customFields 
 */


data class Script (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "src")
    val src: kotlin.String? = null,

    @Json(name = "scope")
    val scope: kotlin.String? = null,

    @Json(name = "event")
    val event: kotlin.String? = null,

    @Json(name = "load_method")
    val loadMethod: kotlin.String? = null,

    @Json(name = "html")
    val html: kotlin.String? = null,

    @Json(name = "created_time")
    val createdTime: A2CDateTime? = null,

    @Json(name = "modified_time")
    val modifiedTime: A2CDateTime? = null,

    @Json(name = "additional_fields")
    val additionalFields: kotlin.Any? = null,

    @Json(name = "custom_fields")
    val customFields: kotlin.Any? = null

) {


}

